// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.

import {
  ethereum,
  JSONValue,
  TypedMap,
  Entity,
  Bytes,
  Address,
  BigInt,
} from "@graphprotocol/graph-ts";

export class EternalFarmingCreated extends ethereum.Event {
  get params(): EternalFarmingCreated__Params {
    return new EternalFarmingCreated__Params(this);
  }
}

export class EternalFarmingCreated__Params {
  _event: EternalFarmingCreated;

  constructor(event: EternalFarmingCreated) {
    this._event = event;
  }

  get rewardToken(): Address {
    return this._event.parameters[0].value.toAddress();
  }

  get bonusRewardToken(): Address {
    return this._event.parameters[1].value.toAddress();
  }

  get pool(): Address {
    return this._event.parameters[2].value.toAddress();
  }

  get virtualPool(): Address {
    return this._event.parameters[3].value.toAddress();
  }

  get startTime(): BigInt {
    return this._event.parameters[4].value.toBigInt();
  }

  get endTime(): BigInt {
    return this._event.parameters[5].value.toBigInt();
  }

  get reward(): BigInt {
    return this._event.parameters[6].value.toBigInt();
  }

  get bonusReward(): BigInt {
    return this._event.parameters[7].value.toBigInt();
  }

  get tiers(): EternalFarmingCreatedTiersStruct {
    return changetype<EternalFarmingCreatedTiersStruct>(
      this._event.parameters[8].value.toTuple(),
    );
  }

  get multiplierToken(): Address {
    return this._event.parameters[9].value.toAddress();
  }

  get minimalAllowedPositionWidth(): i32 {
    return this._event.parameters[10].value.toI32();
  }
}

export class EternalFarmingCreatedTiersStruct extends ethereum.Tuple {
  get tokenAmountForTier1(): BigInt {
    return this[0].toBigInt();
  }

  get tokenAmountForTier2(): BigInt {
    return this[1].toBigInt();
  }

  get tokenAmountForTier3(): BigInt {
    return this[2].toBigInt();
  }

  get tier1Multiplier(): BigInt {
    return this[3].toBigInt();
  }

  get tier2Multiplier(): BigInt {
    return this[4].toBigInt();
  }

  get tier3Multiplier(): BigInt {
    return this[5].toBigInt();
  }
}

export class FarmEnded extends ethereum.Event {
  get params(): FarmEnded__Params {
    return new FarmEnded__Params(this);
  }
}

export class FarmEnded__Params {
  _event: FarmEnded;

  constructor(event: FarmEnded) {
    this._event = event;
  }

  get tokenId(): BigInt {
    return this._event.parameters[0].value.toBigInt();
  }

  get incentiveId(): Bytes {
    return this._event.parameters[1].value.toBytes();
  }

  get rewardAddress(): Address {
    return this._event.parameters[2].value.toAddress();
  }

  get bonusRewardToken(): Address {
    return this._event.parameters[3].value.toAddress();
  }

  get owner(): Address {
    return this._event.parameters[4].value.toAddress();
  }

  get reward(): BigInt {
    return this._event.parameters[5].value.toBigInt();
  }

  get bonusReward(): BigInt {
    return this._event.parameters[6].value.toBigInt();
  }
}

export class FarmEntered extends ethereum.Event {
  get params(): FarmEntered__Params {
    return new FarmEntered__Params(this);
  }
}

export class FarmEntered__Params {
  _event: FarmEntered;

  constructor(event: FarmEntered) {
    this._event = event;
  }

  get tokenId(): BigInt {
    return this._event.parameters[0].value.toBigInt();
  }

  get incentiveId(): Bytes {
    return this._event.parameters[1].value.toBytes();
  }

  get liquidity(): BigInt {
    return this._event.parameters[2].value.toBigInt();
  }

  get tokensLocked(): BigInt {
    return this._event.parameters[3].value.toBigInt();
  }
}

export class FarmingCenter extends ethereum.Event {
  get params(): FarmingCenter__Params {
    return new FarmingCenter__Params(this);
  }
}

export class FarmingCenter__Params {
  _event: FarmingCenter;

  constructor(event: FarmingCenter) {
    this._event = event;
  }

  get farmingCenter(): Address {
    return this._event.parameters[0].value.toAddress();
  }
}

export class IncentiveAttached extends ethereum.Event {
  get params(): IncentiveAttached__Params {
    return new IncentiveAttached__Params(this);
  }
}

export class IncentiveAttached__Params {
  _event: IncentiveAttached;

  constructor(event: IncentiveAttached) {
    this._event = event;
  }

  get rewardToken(): Address {
    return this._event.parameters[0].value.toAddress();
  }

  get bonusRewardToken(): Address {
    return this._event.parameters[1].value.toAddress();
  }

  get pool(): Address {
    return this._event.parameters[2].value.toAddress();
  }

  get virtualPool(): Address {
    return this._event.parameters[3].value.toAddress();
  }

  get startTime(): BigInt {
    return this._event.parameters[4].value.toBigInt();
  }

  get endTime(): BigInt {
    return this._event.parameters[5].value.toBigInt();
  }
}

export class IncentiveDetached extends ethereum.Event {
  get params(): IncentiveDetached__Params {
    return new IncentiveDetached__Params(this);
  }
}

export class IncentiveDetached__Params {
  _event: IncentiveDetached;

  constructor(event: IncentiveDetached) {
    this._event = event;
  }

  get rewardToken(): Address {
    return this._event.parameters[0].value.toAddress();
  }

  get bonusRewardToken(): Address {
    return this._event.parameters[1].value.toAddress();
  }

  get pool(): Address {
    return this._event.parameters[2].value.toAddress();
  }

  get virtualPool(): Address {
    return this._event.parameters[3].value.toAddress();
  }

  get startTime(): BigInt {
    return this._event.parameters[4].value.toBigInt();
  }

  get endTime(): BigInt {
    return this._event.parameters[5].value.toBigInt();
  }
}

export class IncentiveMaker extends ethereum.Event {
  get params(): IncentiveMaker__Params {
    return new IncentiveMaker__Params(this);
  }
}

export class IncentiveMaker__Params {
  _event: IncentiveMaker;

  constructor(event: IncentiveMaker) {
    this._event = event;
  }

  get incentiveMaker(): Address {
    return this._event.parameters[0].value.toAddress();
  }
}

export class RewardClaimed extends ethereum.Event {
  get params(): RewardClaimed__Params {
    return new RewardClaimed__Params(this);
  }
}

export class RewardClaimed__Params {
  _event: RewardClaimed;

  constructor(event: RewardClaimed) {
    this._event = event;
  }

  get to(): Address {
    return this._event.parameters[0].value.toAddress();
  }

  get reward(): BigInt {
    return this._event.parameters[1].value.toBigInt();
  }

  get rewardAddress(): Address {
    return this._event.parameters[2].value.toAddress();
  }

  get owner(): Address {
    return this._event.parameters[3].value.toAddress();
  }
}

export class RewardsAdded extends ethereum.Event {
  get params(): RewardsAdded__Params {
    return new RewardsAdded__Params(this);
  }
}

export class RewardsAdded__Params {
  _event: RewardsAdded;

  constructor(event: RewardsAdded) {
    this._event = event;
  }

  get rewardAmount(): BigInt {
    return this._event.parameters[0].value.toBigInt();
  }

  get bonusRewardAmount(): BigInt {
    return this._event.parameters[1].value.toBigInt();
  }

  get incentiveId(): Bytes {
    return this._event.parameters[2].value.toBytes();
  }
}

export class RewardsCollected extends ethereum.Event {
  get params(): RewardsCollected__Params {
    return new RewardsCollected__Params(this);
  }
}

export class RewardsCollected__Params {
  _event: RewardsCollected;

  constructor(event: RewardsCollected) {
    this._event = event;
  }

  get tokenId(): BigInt {
    return this._event.parameters[0].value.toBigInt();
  }

  get incentiveId(): Bytes {
    return this._event.parameters[1].value.toBytes();
  }

  get rewardAmount(): BigInt {
    return this._event.parameters[2].value.toBigInt();
  }

  get bonusRewardAmount(): BigInt {
    return this._event.parameters[3].value.toBigInt();
  }
}

export class RewardsRatesChanged extends ethereum.Event {
  get params(): RewardsRatesChanged__Params {
    return new RewardsRatesChanged__Params(this);
  }
}

export class RewardsRatesChanged__Params {
  _event: RewardsRatesChanged;

  constructor(event: RewardsRatesChanged) {
    this._event = event;
  }

  get rewardRate(): BigInt {
    return this._event.parameters[0].value.toBigInt();
  }

  get bonusRewardRate(): BigInt {
    return this._event.parameters[1].value.toBigInt();
  }

  get incentiveId(): Bytes {
    return this._event.parameters[2].value.toBytes();
  }
}

export class EternalFarming__collectRewardsResult {
  value0: BigInt;
  value1: BigInt;

  constructor(value0: BigInt, value1: BigInt) {
    this.value0 = value0;
    this.value1 = value1;
  }

  toMap(): TypedMap<string, ethereum.Value> {
    let map = new TypedMap<string, ethereum.Value>();
    map.set("value0", ethereum.Value.fromUnsignedBigInt(this.value0));
    map.set("value1", ethereum.Value.fromUnsignedBigInt(this.value1));
    return map;
  }

  getReward(): BigInt {
    return this.value0;
  }

  getBonusReward(): BigInt {
    return this.value1;
  }
}

export class EternalFarming__collectRewardsInputKeyStruct extends ethereum.Tuple {
  get rewardToken(): Address {
    return this[0].toAddress();
  }

  get bonusRewardToken(): Address {
    return this[1].toAddress();
  }

  get pool(): Address {
    return this[2].toAddress();
  }

  get startTime(): BigInt {
    return this[3].toBigInt();
  }

  get endTime(): BigInt {
    return this[4].toBigInt();
  }
}

export class EternalFarming__createEternalFarmingInputKeyStruct extends ethereum.Tuple {
  get rewardToken(): Address {
    return this[0].toAddress();
  }

  get bonusRewardToken(): Address {
    return this[1].toAddress();
  }

  get pool(): Address {
    return this[2].toAddress();
  }

  get startTime(): BigInt {
    return this[3].toBigInt();
  }

  get endTime(): BigInt {
    return this[4].toBigInt();
  }
}

export class EternalFarming__createEternalFarmingInputParamsStruct extends ethereum.Tuple {
  get reward(): BigInt {
    return this[0].toBigInt();
  }

  get bonusReward(): BigInt {
    return this[1].toBigInt();
  }

  get rewardRate(): BigInt {
    return this[2].toBigInt();
  }

  get bonusRewardRate(): BigInt {
    return this[3].toBigInt();
  }

  get minimalPositionWidth(): i32 {
    return this[4].toI32();
  }

  get multiplierToken(): Address {
    return this[5].toAddress();
  }
}

export class EternalFarming__createEternalFarmingInputTiersStruct extends ethereum.Tuple {
  get tokenAmountForTier1(): BigInt {
    return this[0].toBigInt();
  }

  get tokenAmountForTier2(): BigInt {
    return this[1].toBigInt();
  }

  get tokenAmountForTier3(): BigInt {
    return this[2].toBigInt();
  }

  get tier1Multiplier(): BigInt {
    return this[3].toBigInt();
  }

  get tier2Multiplier(): BigInt {
    return this[4].toBigInt();
  }

  get tier3Multiplier(): BigInt {
    return this[5].toBigInt();
  }
}

export class EternalFarming__farmsResult {
  value0: BigInt;
  value1: i32;
  value2: i32;
  value3: BigInt;
  value4: BigInt;

  constructor(
    value0: BigInt,
    value1: i32,
    value2: i32,
    value3: BigInt,
    value4: BigInt,
  ) {
    this.value0 = value0;
    this.value1 = value1;
    this.value2 = value2;
    this.value3 = value3;
    this.value4 = value4;
  }

  toMap(): TypedMap<string, ethereum.Value> {
    let map = new TypedMap<string, ethereum.Value>();
    map.set("value0", ethereum.Value.fromUnsignedBigInt(this.value0));
    map.set("value1", ethereum.Value.fromI32(this.value1));
    map.set("value2", ethereum.Value.fromI32(this.value2));
    map.set("value3", ethereum.Value.fromUnsignedBigInt(this.value3));
    map.set("value4", ethereum.Value.fromUnsignedBigInt(this.value4));
    return map;
  }

  getLiquidity(): BigInt {
    return this.value0;
  }

  getTickLower(): i32 {
    return this.value1;
  }

  getTickUpper(): i32 {
    return this.value2;
  }

  getInnerRewardGrowth0(): BigInt {
    return this.value3;
  }

  getInnerRewardGrowth1(): BigInt {
    return this.value4;
  }
}

export class EternalFarming__getRewardInfoResult {
  value0: BigInt;
  value1: BigInt;

  constructor(value0: BigInt, value1: BigInt) {
    this.value0 = value0;
    this.value1 = value1;
  }

  toMap(): TypedMap<string, ethereum.Value> {
    let map = new TypedMap<string, ethereum.Value>();
    map.set("value0", ethereum.Value.fromUnsignedBigInt(this.value0));
    map.set("value1", ethereum.Value.fromUnsignedBigInt(this.value1));
    return map;
  }

  getReward(): BigInt {
    return this.value0;
  }

  getBonusReward(): BigInt {
    return this.value1;
  }
}

export class EternalFarming__getRewardInfoInputKeyStruct extends ethereum.Tuple {
  get rewardToken(): Address {
    return this[0].toAddress();
  }

  get bonusRewardToken(): Address {
    return this[1].toAddress();
  }

  get pool(): Address {
    return this[2].toAddress();
  }

  get startTime(): BigInt {
    return this[3].toBigInt();
  }

  get endTime(): BigInt {
    return this[4].toBigInt();
  }
}

export class EternalFarming__incentivesResultTiersStruct extends ethereum.Tuple {
  get tokenAmountForTier1(): BigInt {
    return this[0].toBigInt();
  }

  get tokenAmountForTier2(): BigInt {
    return this[1].toBigInt();
  }

  get tokenAmountForTier3(): BigInt {
    return this[2].toBigInt();
  }

  get tier1Multiplier(): BigInt {
    return this[3].toBigInt();
  }

  get tier2Multiplier(): BigInt {
    return this[4].toBigInt();
  }

  get tier3Multiplier(): BigInt {
    return this[5].toBigInt();
  }
}

export class EternalFarming__incentivesResult {
  value0: BigInt;
  value1: BigInt;
  value2: Address;
  value3: i32;
  value4: BigInt;
  value5: Address;
  value6: EternalFarming__incentivesResultTiersStruct;

  constructor(
    value0: BigInt,
    value1: BigInt,
    value2: Address,
    value3: i32,
    value4: BigInt,
    value5: Address,
    value6: EternalFarming__incentivesResultTiersStruct,
  ) {
    this.value0 = value0;
    this.value1 = value1;
    this.value2 = value2;
    this.value3 = value3;
    this.value4 = value4;
    this.value5 = value5;
    this.value6 = value6;
  }

  toMap(): TypedMap<string, ethereum.Value> {
    let map = new TypedMap<string, ethereum.Value>();
    map.set("value0", ethereum.Value.fromUnsignedBigInt(this.value0));
    map.set("value1", ethereum.Value.fromUnsignedBigInt(this.value1));
    map.set("value2", ethereum.Value.fromAddress(this.value2));
    map.set(
      "value3",
      ethereum.Value.fromUnsignedBigInt(BigInt.fromI32(this.value3)),
    );
    map.set("value4", ethereum.Value.fromUnsignedBigInt(this.value4));
    map.set("value5", ethereum.Value.fromAddress(this.value5));
    map.set("value6", ethereum.Value.fromTuple(this.value6));
    return map;
  }

  getTotalReward(): BigInt {
    return this.value0;
  }

  getBonusReward(): BigInt {
    return this.value1;
  }

  getVirtualPoolAddress(): Address {
    return this.value2;
  }

  getMinimalPositionWidth(): i32 {
    return this.value3;
  }

  getTotalLiquidity(): BigInt {
    return this.value4;
  }

  getMultiplierToken(): Address {
    return this.value5;
  }

  getTiers(): EternalFarming__incentivesResultTiersStruct {
    return this.value6;
  }
}

export class EternalFarming extends ethereum.SmartContract {
  static bind(address: Address): EternalFarming {
    return new EternalFarming("EternalFarming", address);
  }

  claimReward(
    rewardToken: Address,
    to: Address,
    amountRequested: BigInt,
  ): BigInt {
    let result = super.call(
      "claimReward",
      "claimReward(address,address,uint256):(uint256)",
      [
        ethereum.Value.fromAddress(rewardToken),
        ethereum.Value.fromAddress(to),
        ethereum.Value.fromUnsignedBigInt(amountRequested),
      ],
    );

    return result[0].toBigInt();
  }

  try_claimReward(
    rewardToken: Address,
    to: Address,
    amountRequested: BigInt,
  ): ethereum.CallResult<BigInt> {
    let result = super.tryCall(
      "claimReward",
      "claimReward(address,address,uint256):(uint256)",
      [
        ethereum.Value.fromAddress(rewardToken),
        ethereum.Value.fromAddress(to),
        ethereum.Value.fromUnsignedBigInt(amountRequested),
      ],
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBigInt());
  }

  claimRewardFrom(
    rewardToken: Address,
    from: Address,
    to: Address,
    amountRequested: BigInt,
  ): BigInt {
    let result = super.call(
      "claimRewardFrom",
      "claimRewardFrom(address,address,address,uint256):(uint256)",
      [
        ethereum.Value.fromAddress(rewardToken),
        ethereum.Value.fromAddress(from),
        ethereum.Value.fromAddress(to),
        ethereum.Value.fromUnsignedBigInt(amountRequested),
      ],
    );

    return result[0].toBigInt();
  }

  try_claimRewardFrom(
    rewardToken: Address,
    from: Address,
    to: Address,
    amountRequested: BigInt,
  ): ethereum.CallResult<BigInt> {
    let result = super.tryCall(
      "claimRewardFrom",
      "claimRewardFrom(address,address,address,uint256):(uint256)",
      [
        ethereum.Value.fromAddress(rewardToken),
        ethereum.Value.fromAddress(from),
        ethereum.Value.fromAddress(to),
        ethereum.Value.fromUnsignedBigInt(amountRequested),
      ],
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBigInt());
  }

  collectRewards(
    key: EternalFarming__collectRewardsInputKeyStruct,
    tokenId: BigInt,
    _owner: Address,
  ): EternalFarming__collectRewardsResult {
    let result = super.call(
      "collectRewards",
      "collectRewards((address,address,address,uint256,uint256),uint256,address):(uint256,uint256)",
      [
        ethereum.Value.fromTuple(key),
        ethereum.Value.fromUnsignedBigInt(tokenId),
        ethereum.Value.fromAddress(_owner),
      ],
    );

    return new EternalFarming__collectRewardsResult(
      result[0].toBigInt(),
      result[1].toBigInt(),
    );
  }

  try_collectRewards(
    key: EternalFarming__collectRewardsInputKeyStruct,
    tokenId: BigInt,
    _owner: Address,
  ): ethereum.CallResult<EternalFarming__collectRewardsResult> {
    let result = super.tryCall(
      "collectRewards",
      "collectRewards((address,address,address,uint256,uint256),uint256,address):(uint256,uint256)",
      [
        ethereum.Value.fromTuple(key),
        ethereum.Value.fromUnsignedBigInt(tokenId),
        ethereum.Value.fromAddress(_owner),
      ],
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(
      new EternalFarming__collectRewardsResult(
        value[0].toBigInt(),
        value[1].toBigInt(),
      ),
    );
  }

  createEternalFarming(
    key: EternalFarming__createEternalFarmingInputKeyStruct,
    params: EternalFarming__createEternalFarmingInputParamsStruct,
    tiers: EternalFarming__createEternalFarmingInputTiersStruct,
  ): Address {
    let result = super.call(
      "createEternalFarming",
      "createEternalFarming((address,address,address,uint256,uint256),(uint256,uint256,uint128,uint128,uint24,address),(uint256,uint256,uint256,uint32,uint32,uint32)):(address)",
      [
        ethereum.Value.fromTuple(key),
        ethereum.Value.fromTuple(params),
        ethereum.Value.fromTuple(tiers),
      ],
    );

    return result[0].toAddress();
  }

  try_createEternalFarming(
    key: EternalFarming__createEternalFarmingInputKeyStruct,
    params: EternalFarming__createEternalFarmingInputParamsStruct,
    tiers: EternalFarming__createEternalFarmingInputTiersStruct,
  ): ethereum.CallResult<Address> {
    let result = super.tryCall(
      "createEternalFarming",
      "createEternalFarming((address,address,address,uint256,uint256),(uint256,uint256,uint128,uint128,uint24,address),(uint256,uint256,uint256,uint32,uint32,uint32)):(address)",
      [
        ethereum.Value.fromTuple(key),
        ethereum.Value.fromTuple(params),
        ethereum.Value.fromTuple(tiers),
      ],
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toAddress());
  }

  deployer(): Address {
    let result = super.call("deployer", "deployer():(address)", []);

    return result[0].toAddress();
  }

  try_deployer(): ethereum.CallResult<Address> {
    let result = super.tryCall("deployer", "deployer():(address)", []);
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toAddress());
  }

  farmingCenter(): Address {
    let result = super.call("farmingCenter", "farmingCenter():(address)", []);

    return result[0].toAddress();
  }

  try_farmingCenter(): ethereum.CallResult<Address> {
    let result = super.tryCall(
      "farmingCenter",
      "farmingCenter():(address)",
      [],
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toAddress());
  }

  farms(param0: BigInt, param1: Bytes): EternalFarming__farmsResult {
    let result = super.call(
      "farms",
      "farms(uint256,bytes32):(uint128,int24,int24,uint256,uint256)",
      [
        ethereum.Value.fromUnsignedBigInt(param0),
        ethereum.Value.fromFixedBytes(param1),
      ],
    );

    return new EternalFarming__farmsResult(
      result[0].toBigInt(),
      result[1].toI32(),
      result[2].toI32(),
      result[3].toBigInt(),
      result[4].toBigInt(),
    );
  }

  try_farms(
    param0: BigInt,
    param1: Bytes,
  ): ethereum.CallResult<EternalFarming__farmsResult> {
    let result = super.tryCall(
      "farms",
      "farms(uint256,bytes32):(uint128,int24,int24,uint256,uint256)",
      [
        ethereum.Value.fromUnsignedBigInt(param0),
        ethereum.Value.fromFixedBytes(param1),
      ],
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(
      new EternalFarming__farmsResult(
        value[0].toBigInt(),
        value[1].toI32(),
        value[2].toI32(),
        value[3].toBigInt(),
        value[4].toBigInt(),
      ),
    );
  }

  getRewardInfo(
    key: EternalFarming__getRewardInfoInputKeyStruct,
    tokenId: BigInt,
  ): EternalFarming__getRewardInfoResult {
    let result = super.call(
      "getRewardInfo",
      "getRewardInfo((address,address,address,uint256,uint256),uint256):(uint256,uint256)",
      [
        ethereum.Value.fromTuple(key),
        ethereum.Value.fromUnsignedBigInt(tokenId),
      ],
    );

    return new EternalFarming__getRewardInfoResult(
      result[0].toBigInt(),
      result[1].toBigInt(),
    );
  }

  try_getRewardInfo(
    key: EternalFarming__getRewardInfoInputKeyStruct,
    tokenId: BigInt,
  ): ethereum.CallResult<EternalFarming__getRewardInfoResult> {
    let result = super.tryCall(
      "getRewardInfo",
      "getRewardInfo((address,address,address,uint256,uint256),uint256):(uint256,uint256)",
      [
        ethereum.Value.fromTuple(key),
        ethereum.Value.fromUnsignedBigInt(tokenId),
      ],
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(
      new EternalFarming__getRewardInfoResult(
        value[0].toBigInt(),
        value[1].toBigInt(),
      ),
    );
  }

  incentives(param0: Bytes): EternalFarming__incentivesResult {
    let result = super.call(
      "incentives",
      "incentives(bytes32):(uint256,uint256,address,uint24,uint224,address,(uint256,uint256,uint256,uint32,uint32,uint32))",
      [ethereum.Value.fromFixedBytes(param0)],
    );

    return new EternalFarming__incentivesResult(
      result[0].toBigInt(),
      result[1].toBigInt(),
      result[2].toAddress(),
      result[3].toI32(),
      result[4].toBigInt(),
      result[5].toAddress(),
      changetype<EternalFarming__incentivesResultTiersStruct>(
        result[6].toTuple(),
      ),
    );
  }

  try_incentives(
    param0: Bytes,
  ): ethereum.CallResult<EternalFarming__incentivesResult> {
    let result = super.tryCall(
      "incentives",
      "incentives(bytes32):(uint256,uint256,address,uint24,uint224,address,(uint256,uint256,uint256,uint32,uint32,uint32))",
      [ethereum.Value.fromFixedBytes(param0)],
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(
      new EternalFarming__incentivesResult(
        value[0].toBigInt(),
        value[1].toBigInt(),
        value[2].toAddress(),
        value[3].toI32(),
        value[4].toBigInt(),
        value[5].toAddress(),
        changetype<EternalFarming__incentivesResultTiersStruct>(
          value[6].toTuple(),
        ),
      ),
    );
  }

  nonfungiblePositionManager(): Address {
    let result = super.call(
      "nonfungiblePositionManager",
      "nonfungiblePositionManager():(address)",
      [],
    );

    return result[0].toAddress();
  }

  try_nonfungiblePositionManager(): ethereum.CallResult<Address> {
    let result = super.tryCall(
      "nonfungiblePositionManager",
      "nonfungiblePositionManager():(address)",
      [],
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toAddress());
  }

  rewards(param0: Address, param1: Address): BigInt {
    let result = super.call("rewards", "rewards(address,address):(uint256)", [
      ethereum.Value.fromAddress(param0),
      ethereum.Value.fromAddress(param1),
    ]);

    return result[0].toBigInt();
  }

  try_rewards(param0: Address, param1: Address): ethereum.CallResult<BigInt> {
    let result = super.tryCall(
      "rewards",
      "rewards(address,address):(uint256)",
      [ethereum.Value.fromAddress(param0), ethereum.Value.fromAddress(param1)],
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBigInt());
  }
}

export class ConstructorCall extends ethereum.Call {
  get inputs(): ConstructorCall__Inputs {
    return new ConstructorCall__Inputs(this);
  }

  get outputs(): ConstructorCall__Outputs {
    return new ConstructorCall__Outputs(this);
  }
}

export class ConstructorCall__Inputs {
  _call: ConstructorCall;

  constructor(call: ConstructorCall) {
    this._call = call;
  }

  get _deployer(): Address {
    return this._call.inputValues[0].value.toAddress();
  }

  get _nonfungiblePositionManager(): Address {
    return this._call.inputValues[1].value.toAddress();
  }
}

export class ConstructorCall__Outputs {
  _call: ConstructorCall;

  constructor(call: ConstructorCall) {
    this._call = call;
  }
}

export class AddRewardsCall extends ethereum.Call {
  get inputs(): AddRewardsCall__Inputs {
    return new AddRewardsCall__Inputs(this);
  }

  get outputs(): AddRewardsCall__Outputs {
    return new AddRewardsCall__Outputs(this);
  }
}

export class AddRewardsCall__Inputs {
  _call: AddRewardsCall;

  constructor(call: AddRewardsCall) {
    this._call = call;
  }

  get key(): AddRewardsCallKeyStruct {
    return changetype<AddRewardsCallKeyStruct>(
      this._call.inputValues[0].value.toTuple(),
    );
  }

  get rewardAmount(): BigInt {
    return this._call.inputValues[1].value.toBigInt();
  }

  get bonusRewardAmount(): BigInt {
    return this._call.inputValues[2].value.toBigInt();
  }
}

export class AddRewardsCall__Outputs {
  _call: AddRewardsCall;

  constructor(call: AddRewardsCall) {
    this._call = call;
  }
}

export class AddRewardsCallKeyStruct extends ethereum.Tuple {
  get rewardToken(): Address {
    return this[0].toAddress();
  }

  get bonusRewardToken(): Address {
    return this[1].toAddress();
  }

  get pool(): Address {
    return this[2].toAddress();
  }

  get startTime(): BigInt {
    return this[3].toBigInt();
  }

  get endTime(): BigInt {
    return this[4].toBigInt();
  }
}

export class AttachIncentiveCall extends ethereum.Call {
  get inputs(): AttachIncentiveCall__Inputs {
    return new AttachIncentiveCall__Inputs(this);
  }

  get outputs(): AttachIncentiveCall__Outputs {
    return new AttachIncentiveCall__Outputs(this);
  }
}

export class AttachIncentiveCall__Inputs {
  _call: AttachIncentiveCall;

  constructor(call: AttachIncentiveCall) {
    this._call = call;
  }

  get key(): AttachIncentiveCallKeyStruct {
    return changetype<AttachIncentiveCallKeyStruct>(
      this._call.inputValues[0].value.toTuple(),
    );
  }
}

export class AttachIncentiveCall__Outputs {
  _call: AttachIncentiveCall;

  constructor(call: AttachIncentiveCall) {
    this._call = call;
  }
}

export class AttachIncentiveCallKeyStruct extends ethereum.Tuple {
  get rewardToken(): Address {
    return this[0].toAddress();
  }

  get bonusRewardToken(): Address {
    return this[1].toAddress();
  }

  get pool(): Address {
    return this[2].toAddress();
  }

  get startTime(): BigInt {
    return this[3].toBigInt();
  }

  get endTime(): BigInt {
    return this[4].toBigInt();
  }
}

export class ClaimRewardCall extends ethereum.Call {
  get inputs(): ClaimRewardCall__Inputs {
    return new ClaimRewardCall__Inputs(this);
  }

  get outputs(): ClaimRewardCall__Outputs {
    return new ClaimRewardCall__Outputs(this);
  }
}

export class ClaimRewardCall__Inputs {
  _call: ClaimRewardCall;

  constructor(call: ClaimRewardCall) {
    this._call = call;
  }

  get rewardToken(): Address {
    return this._call.inputValues[0].value.toAddress();
  }

  get to(): Address {
    return this._call.inputValues[1].value.toAddress();
  }

  get amountRequested(): BigInt {
    return this._call.inputValues[2].value.toBigInt();
  }
}

export class ClaimRewardCall__Outputs {
  _call: ClaimRewardCall;

  constructor(call: ClaimRewardCall) {
    this._call = call;
  }

  get reward(): BigInt {
    return this._call.outputValues[0].value.toBigInt();
  }
}

export class ClaimRewardFromCall extends ethereum.Call {
  get inputs(): ClaimRewardFromCall__Inputs {
    return new ClaimRewardFromCall__Inputs(this);
  }

  get outputs(): ClaimRewardFromCall__Outputs {
    return new ClaimRewardFromCall__Outputs(this);
  }
}

export class ClaimRewardFromCall__Inputs {
  _call: ClaimRewardFromCall;

  constructor(call: ClaimRewardFromCall) {
    this._call = call;
  }

  get rewardToken(): Address {
    return this._call.inputValues[0].value.toAddress();
  }

  get from(): Address {
    return this._call.inputValues[1].value.toAddress();
  }

  get to(): Address {
    return this._call.inputValues[2].value.toAddress();
  }

  get amountRequested(): BigInt {
    return this._call.inputValues[3].value.toBigInt();
  }
}

export class ClaimRewardFromCall__Outputs {
  _call: ClaimRewardFromCall;

  constructor(call: ClaimRewardFromCall) {
    this._call = call;
  }

  get reward(): BigInt {
    return this._call.outputValues[0].value.toBigInt();
  }
}

export class CollectRewardsCall extends ethereum.Call {
  get inputs(): CollectRewardsCall__Inputs {
    return new CollectRewardsCall__Inputs(this);
  }

  get outputs(): CollectRewardsCall__Outputs {
    return new CollectRewardsCall__Outputs(this);
  }
}

export class CollectRewardsCall__Inputs {
  _call: CollectRewardsCall;

  constructor(call: CollectRewardsCall) {
    this._call = call;
  }

  get key(): CollectRewardsCallKeyStruct {
    return changetype<CollectRewardsCallKeyStruct>(
      this._call.inputValues[0].value.toTuple(),
    );
  }

  get tokenId(): BigInt {
    return this._call.inputValues[1].value.toBigInt();
  }

  get _owner(): Address {
    return this._call.inputValues[2].value.toAddress();
  }
}

export class CollectRewardsCall__Outputs {
  _call: CollectRewardsCall;

  constructor(call: CollectRewardsCall) {
    this._call = call;
  }

  get reward(): BigInt {
    return this._call.outputValues[0].value.toBigInt();
  }

  get bonusReward(): BigInt {
    return this._call.outputValues[1].value.toBigInt();
  }
}

export class CollectRewardsCallKeyStruct extends ethereum.Tuple {
  get rewardToken(): Address {
    return this[0].toAddress();
  }

  get bonusRewardToken(): Address {
    return this[1].toAddress();
  }

  get pool(): Address {
    return this[2].toAddress();
  }

  get startTime(): BigInt {
    return this[3].toBigInt();
  }

  get endTime(): BigInt {
    return this[4].toBigInt();
  }
}

export class CreateEternalFarmingCall extends ethereum.Call {
  get inputs(): CreateEternalFarmingCall__Inputs {
    return new CreateEternalFarmingCall__Inputs(this);
  }

  get outputs(): CreateEternalFarmingCall__Outputs {
    return new CreateEternalFarmingCall__Outputs(this);
  }
}

export class CreateEternalFarmingCall__Inputs {
  _call: CreateEternalFarmingCall;

  constructor(call: CreateEternalFarmingCall) {
    this._call = call;
  }

  get key(): CreateEternalFarmingCallKeyStruct {
    return changetype<CreateEternalFarmingCallKeyStruct>(
      this._call.inputValues[0].value.toTuple(),
    );
  }

  get params(): CreateEternalFarmingCallParamsStruct {
    return changetype<CreateEternalFarmingCallParamsStruct>(
      this._call.inputValues[1].value.toTuple(),
    );
  }

  get tiers(): CreateEternalFarmingCallTiersStruct {
    return changetype<CreateEternalFarmingCallTiersStruct>(
      this._call.inputValues[2].value.toTuple(),
    );
  }
}

export class CreateEternalFarmingCall__Outputs {
  _call: CreateEternalFarmingCall;

  constructor(call: CreateEternalFarmingCall) {
    this._call = call;
  }

  get virtualPool(): Address {
    return this._call.outputValues[0].value.toAddress();
  }
}

export class CreateEternalFarmingCallKeyStruct extends ethereum.Tuple {
  get rewardToken(): Address {
    return this[0].toAddress();
  }

  get bonusRewardToken(): Address {
    return this[1].toAddress();
  }

  get pool(): Address {
    return this[2].toAddress();
  }

  get startTime(): BigInt {
    return this[3].toBigInt();
  }

  get endTime(): BigInt {
    return this[4].toBigInt();
  }
}

export class CreateEternalFarmingCallParamsStruct extends ethereum.Tuple {
  get reward(): BigInt {
    return this[0].toBigInt();
  }

  get bonusReward(): BigInt {
    return this[1].toBigInt();
  }

  get rewardRate(): BigInt {
    return this[2].toBigInt();
  }

  get bonusRewardRate(): BigInt {
    return this[3].toBigInt();
  }

  get minimalPositionWidth(): i32 {
    return this[4].toI32();
  }

  get multiplierToken(): Address {
    return this[5].toAddress();
  }
}

export class CreateEternalFarmingCallTiersStruct extends ethereum.Tuple {
  get tokenAmountForTier1(): BigInt {
    return this[0].toBigInt();
  }

  get tokenAmountForTier2(): BigInt {
    return this[1].toBigInt();
  }

  get tokenAmountForTier3(): BigInt {
    return this[2].toBigInt();
  }

  get tier1Multiplier(): BigInt {
    return this[3].toBigInt();
  }

  get tier2Multiplier(): BigInt {
    return this[4].toBigInt();
  }

  get tier3Multiplier(): BigInt {
    return this[5].toBigInt();
  }
}

export class DetachIncentiveCall extends ethereum.Call {
  get inputs(): DetachIncentiveCall__Inputs {
    return new DetachIncentiveCall__Inputs(this);
  }

  get outputs(): DetachIncentiveCall__Outputs {
    return new DetachIncentiveCall__Outputs(this);
  }
}

export class DetachIncentiveCall__Inputs {
  _call: DetachIncentiveCall;

  constructor(call: DetachIncentiveCall) {
    this._call = call;
  }

  get key(): DetachIncentiveCallKeyStruct {
    return changetype<DetachIncentiveCallKeyStruct>(
      this._call.inputValues[0].value.toTuple(),
    );
  }
}

export class DetachIncentiveCall__Outputs {
  _call: DetachIncentiveCall;

  constructor(call: DetachIncentiveCall) {
    this._call = call;
  }
}

export class DetachIncentiveCallKeyStruct extends ethereum.Tuple {
  get rewardToken(): Address {
    return this[0].toAddress();
  }

  get bonusRewardToken(): Address {
    return this[1].toAddress();
  }

  get pool(): Address {
    return this[2].toAddress();
  }

  get startTime(): BigInt {
    return this[3].toBigInt();
  }

  get endTime(): BigInt {
    return this[4].toBigInt();
  }
}

export class EnterFarmingCall extends ethereum.Call {
  get inputs(): EnterFarmingCall__Inputs {
    return new EnterFarmingCall__Inputs(this);
  }

  get outputs(): EnterFarmingCall__Outputs {
    return new EnterFarmingCall__Outputs(this);
  }
}

export class EnterFarmingCall__Inputs {
  _call: EnterFarmingCall;

  constructor(call: EnterFarmingCall) {
    this._call = call;
  }

  get key(): EnterFarmingCallKeyStruct {
    return changetype<EnterFarmingCallKeyStruct>(
      this._call.inputValues[0].value.toTuple(),
    );
  }

  get tokenId(): BigInt {
    return this._call.inputValues[1].value.toBigInt();
  }

  get tokensLocked(): BigInt {
    return this._call.inputValues[2].value.toBigInt();
  }
}

export class EnterFarmingCall__Outputs {
  _call: EnterFarmingCall;

  constructor(call: EnterFarmingCall) {
    this._call = call;
  }
}

export class EnterFarmingCallKeyStruct extends ethereum.Tuple {
  get rewardToken(): Address {
    return this[0].toAddress();
  }

  get bonusRewardToken(): Address {
    return this[1].toAddress();
  }

  get pool(): Address {
    return this[2].toAddress();
  }

  get startTime(): BigInt {
    return this[3].toBigInt();
  }

  get endTime(): BigInt {
    return this[4].toBigInt();
  }
}

export class ExitFarmingCall extends ethereum.Call {
  get inputs(): ExitFarmingCall__Inputs {
    return new ExitFarmingCall__Inputs(this);
  }

  get outputs(): ExitFarmingCall__Outputs {
    return new ExitFarmingCall__Outputs(this);
  }
}

export class ExitFarmingCall__Inputs {
  _call: ExitFarmingCall;

  constructor(call: ExitFarmingCall) {
    this._call = call;
  }

  get key(): ExitFarmingCallKeyStruct {
    return changetype<ExitFarmingCallKeyStruct>(
      this._call.inputValues[0].value.toTuple(),
    );
  }

  get tokenId(): BigInt {
    return this._call.inputValues[1].value.toBigInt();
  }

  get _owner(): Address {
    return this._call.inputValues[2].value.toAddress();
  }
}

export class ExitFarmingCall__Outputs {
  _call: ExitFarmingCall;

  constructor(call: ExitFarmingCall) {
    this._call = call;
  }
}

export class ExitFarmingCallKeyStruct extends ethereum.Tuple {
  get rewardToken(): Address {
    return this[0].toAddress();
  }

  get bonusRewardToken(): Address {
    return this[1].toAddress();
  }

  get pool(): Address {
    return this[2].toAddress();
  }

  get startTime(): BigInt {
    return this[3].toBigInt();
  }

  get endTime(): BigInt {
    return this[4].toBigInt();
  }
}

export class SetFarmingCenterAddressCall extends ethereum.Call {
  get inputs(): SetFarmingCenterAddressCall__Inputs {
    return new SetFarmingCenterAddressCall__Inputs(this);
  }

  get outputs(): SetFarmingCenterAddressCall__Outputs {
    return new SetFarmingCenterAddressCall__Outputs(this);
  }
}

export class SetFarmingCenterAddressCall__Inputs {
  _call: SetFarmingCenterAddressCall;

  constructor(call: SetFarmingCenterAddressCall) {
    this._call = call;
  }

  get _farmingCenter(): Address {
    return this._call.inputValues[0].value.toAddress();
  }
}

export class SetFarmingCenterAddressCall__Outputs {
  _call: SetFarmingCenterAddressCall;

  constructor(call: SetFarmingCenterAddressCall) {
    this._call = call;
  }
}

export class SetIncentiveMakerCall extends ethereum.Call {
  get inputs(): SetIncentiveMakerCall__Inputs {
    return new SetIncentiveMakerCall__Inputs(this);
  }

  get outputs(): SetIncentiveMakerCall__Outputs {
    return new SetIncentiveMakerCall__Outputs(this);
  }
}

export class SetIncentiveMakerCall__Inputs {
  _call: SetIncentiveMakerCall;

  constructor(call: SetIncentiveMakerCall) {
    this._call = call;
  }

  get _incentiveMaker(): Address {
    return this._call.inputValues[0].value.toAddress();
  }
}

export class SetIncentiveMakerCall__Outputs {
  _call: SetIncentiveMakerCall;

  constructor(call: SetIncentiveMakerCall) {
    this._call = call;
  }
}

export class SetRatesCall extends ethereum.Call {
  get inputs(): SetRatesCall__Inputs {
    return new SetRatesCall__Inputs(this);
  }

  get outputs(): SetRatesCall__Outputs {
    return new SetRatesCall__Outputs(this);
  }
}

export class SetRatesCall__Inputs {
  _call: SetRatesCall;

  constructor(call: SetRatesCall) {
    this._call = call;
  }

  get key(): SetRatesCallKeyStruct {
    return changetype<SetRatesCallKeyStruct>(
      this._call.inputValues[0].value.toTuple(),
    );
  }

  get rewardRate(): BigInt {
    return this._call.inputValues[1].value.toBigInt();
  }

  get bonusRewardRate(): BigInt {
    return this._call.inputValues[2].value.toBigInt();
  }
}

export class SetRatesCall__Outputs {
  _call: SetRatesCall;

  constructor(call: SetRatesCall) {
    this._call = call;
  }
}

export class SetRatesCallKeyStruct extends ethereum.Tuple {
  get rewardToken(): Address {
    return this[0].toAddress();
  }

  get bonusRewardToken(): Address {
    return this[1].toAddress();
  }

  get pool(): Address {
    return this[2].toAddress();
  }

  get startTime(): BigInt {
    return this[3].toBigInt();
  }

  get endTime(): BigInt {
    return this[4].toBigInt();
  }
}
