// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.

import {
  ethereum,
  JSONValue,
  TypedMap,
  Entity,
  Bytes,
  Address,
  BigInt,
} from "@graphprotocol/graph-ts";

export class FarmEnded extends ethereum.Event {
  get params(): FarmEnded__Params {
    return new FarmEnded__Params(this);
  }
}

export class FarmEnded__Params {
  _event: FarmEnded;

  constructor(event: FarmEnded) {
    this._event = event;
  }

  get tokenId(): BigInt {
    return this._event.parameters[0].value.toBigInt();
  }

  get incentiveId(): Bytes {
    return this._event.parameters[1].value.toBytes();
  }

  get rewardAddress(): Address {
    return this._event.parameters[2].value.toAddress();
  }

  get bonusRewardToken(): Address {
    return this._event.parameters[3].value.toAddress();
  }

  get owner(): Address {
    return this._event.parameters[4].value.toAddress();
  }

  get reward(): BigInt {
    return this._event.parameters[5].value.toBigInt();
  }

  get bonusReward(): BigInt {
    return this._event.parameters[6].value.toBigInt();
  }
}

export class FarmEntered extends ethereum.Event {
  get params(): FarmEntered__Params {
    return new FarmEntered__Params(this);
  }
}

export class FarmEntered__Params {
  _event: FarmEntered;

  constructor(event: FarmEntered) {
    this._event = event;
  }

  get tokenId(): BigInt {
    return this._event.parameters[0].value.toBigInt();
  }

  get incentiveId(): Bytes {
    return this._event.parameters[1].value.toBytes();
  }

  get liquidity(): BigInt {
    return this._event.parameters[2].value.toBigInt();
  }

  get tokensLocked(): BigInt {
    return this._event.parameters[3].value.toBigInt();
  }
}

export class FarmingCenter extends ethereum.Event {
  get params(): FarmingCenter__Params {
    return new FarmingCenter__Params(this);
  }
}

export class FarmingCenter__Params {
  _event: FarmingCenter;

  constructor(event: FarmingCenter) {
    this._event = event;
  }

  get farmingCenter(): Address {
    return this._event.parameters[0].value.toAddress();
  }
}

export class IncentiveAttached extends ethereum.Event {
  get params(): IncentiveAttached__Params {
    return new IncentiveAttached__Params(this);
  }
}

export class IncentiveAttached__Params {
  _event: IncentiveAttached;

  constructor(event: IncentiveAttached) {
    this._event = event;
  }

  get rewardToken(): Address {
    return this._event.parameters[0].value.toAddress();
  }

  get bonusRewardToken(): Address {
    return this._event.parameters[1].value.toAddress();
  }

  get pool(): Address {
    return this._event.parameters[2].value.toAddress();
  }

  get virtualPool(): Address {
    return this._event.parameters[3].value.toAddress();
  }

  get startTime(): BigInt {
    return this._event.parameters[4].value.toBigInt();
  }

  get endTime(): BigInt {
    return this._event.parameters[5].value.toBigInt();
  }
}

export class IncentiveDetached extends ethereum.Event {
  get params(): IncentiveDetached__Params {
    return new IncentiveDetached__Params(this);
  }
}

export class IncentiveDetached__Params {
  _event: IncentiveDetached;

  constructor(event: IncentiveDetached) {
    this._event = event;
  }

  get rewardToken(): Address {
    return this._event.parameters[0].value.toAddress();
  }

  get bonusRewardToken(): Address {
    return this._event.parameters[1].value.toAddress();
  }

  get pool(): Address {
    return this._event.parameters[2].value.toAddress();
  }

  get virtualPool(): Address {
    return this._event.parameters[3].value.toAddress();
  }

  get startTime(): BigInt {
    return this._event.parameters[4].value.toBigInt();
  }

  get endTime(): BigInt {
    return this._event.parameters[5].value.toBigInt();
  }
}

export class IncentiveMaker extends ethereum.Event {
  get params(): IncentiveMaker__Params {
    return new IncentiveMaker__Params(this);
  }
}

export class IncentiveMaker__Params {
  _event: IncentiveMaker;

  constructor(event: IncentiveMaker) {
    this._event = event;
  }

  get incentiveMaker(): Address {
    return this._event.parameters[0].value.toAddress();
  }
}

export class LimitFarmingCreated extends ethereum.Event {
  get params(): LimitFarmingCreated__Params {
    return new LimitFarmingCreated__Params(this);
  }
}

export class LimitFarmingCreated__Params {
  _event: LimitFarmingCreated;

  constructor(event: LimitFarmingCreated) {
    this._event = event;
  }

  get rewardToken(): Address {
    return this._event.parameters[0].value.toAddress();
  }

  get bonusRewardToken(): Address {
    return this._event.parameters[1].value.toAddress();
  }

  get pool(): Address {
    return this._event.parameters[2].value.toAddress();
  }

  get startTime(): BigInt {
    return this._event.parameters[3].value.toBigInt();
  }

  get endTime(): BigInt {
    return this._event.parameters[4].value.toBigInt();
  }

  get reward(): BigInt {
    return this._event.parameters[5].value.toBigInt();
  }

  get bonusReward(): BigInt {
    return this._event.parameters[6].value.toBigInt();
  }

  get tiers(): LimitFarmingCreatedTiersStruct {
    return changetype<LimitFarmingCreatedTiersStruct>(
      this._event.parameters[7].value.toTuple(),
    );
  }

  get multiplierToken(): Address {
    return this._event.parameters[8].value.toAddress();
  }

  get minimalAllowedPositionWidth(): i32 {
    return this._event.parameters[9].value.toI32();
  }

  get enterStartTime(): BigInt {
    return this._event.parameters[10].value.toBigInt();
  }
}

export class LimitFarmingCreatedTiersStruct extends ethereum.Tuple {
  get tokenAmountForTier1(): BigInt {
    return this[0].toBigInt();
  }

  get tokenAmountForTier2(): BigInt {
    return this[1].toBigInt();
  }

  get tokenAmountForTier3(): BigInt {
    return this[2].toBigInt();
  }

  get tier1Multiplier(): BigInt {
    return this[3].toBigInt();
  }

  get tier2Multiplier(): BigInt {
    return this[4].toBigInt();
  }

  get tier3Multiplier(): BigInt {
    return this[5].toBigInt();
  }
}

export class RewardAmountsDecreased extends ethereum.Event {
  get params(): RewardAmountsDecreased__Params {
    return new RewardAmountsDecreased__Params(this);
  }
}

export class RewardAmountsDecreased__Params {
  _event: RewardAmountsDecreased;

  constructor(event: RewardAmountsDecreased) {
    this._event = event;
  }

  get reward(): BigInt {
    return this._event.parameters[0].value.toBigInt();
  }

  get bonusReward(): BigInt {
    return this._event.parameters[1].value.toBigInt();
  }

  get incentiveId(): Bytes {
    return this._event.parameters[2].value.toBytes();
  }
}

export class RewardClaimed extends ethereum.Event {
  get params(): RewardClaimed__Params {
    return new RewardClaimed__Params(this);
  }
}

export class RewardClaimed__Params {
  _event: RewardClaimed;

  constructor(event: RewardClaimed) {
    this._event = event;
  }

  get to(): Address {
    return this._event.parameters[0].value.toAddress();
  }

  get reward(): BigInt {
    return this._event.parameters[1].value.toBigInt();
  }

  get rewardAddress(): Address {
    return this._event.parameters[2].value.toAddress();
  }

  get owner(): Address {
    return this._event.parameters[3].value.toAddress();
  }
}

export class RewardsAdded extends ethereum.Event {
  get params(): RewardsAdded__Params {
    return new RewardsAdded__Params(this);
  }
}

export class RewardsAdded__Params {
  _event: RewardsAdded;

  constructor(event: RewardsAdded) {
    this._event = event;
  }

  get rewardAmount(): BigInt {
    return this._event.parameters[0].value.toBigInt();
  }

  get bonusRewardAmount(): BigInt {
    return this._event.parameters[1].value.toBigInt();
  }

  get incentiveId(): Bytes {
    return this._event.parameters[2].value.toBytes();
  }
}

export class LimitFarming__createLimitFarmingInputKeyStruct extends ethereum.Tuple {
  get rewardToken(): Address {
    return this[0].toAddress();
  }

  get bonusRewardToken(): Address {
    return this[1].toAddress();
  }

  get pool(): Address {
    return this[2].toAddress();
  }

  get startTime(): BigInt {
    return this[3].toBigInt();
  }

  get endTime(): BigInt {
    return this[4].toBigInt();
  }
}

export class LimitFarming__createLimitFarmingInputTiersStruct extends ethereum.Tuple {
  get tokenAmountForTier1(): BigInt {
    return this[0].toBigInt();
  }

  get tokenAmountForTier2(): BigInt {
    return this[1].toBigInt();
  }

  get tokenAmountForTier3(): BigInt {
    return this[2].toBigInt();
  }

  get tier1Multiplier(): BigInt {
    return this[3].toBigInt();
  }

  get tier2Multiplier(): BigInt {
    return this[4].toBigInt();
  }

  get tier3Multiplier(): BigInt {
    return this[5].toBigInt();
  }
}

export class LimitFarming__createLimitFarmingInputParamsStruct extends ethereum.Tuple {
  get reward(): BigInt {
    return this[0].toBigInt();
  }

  get bonusReward(): BigInt {
    return this[1].toBigInt();
  }

  get minimalPositionWidth(): i32 {
    return this[2].toI32();
  }

  get multiplierToken(): Address {
    return this[3].toAddress();
  }

  get enterStartTime(): BigInt {
    return this[4].toBigInt();
  }
}

export class LimitFarming__farmsResult {
  value0: BigInt;
  value1: i32;
  value2: i32;

  constructor(value0: BigInt, value1: i32, value2: i32) {
    this.value0 = value0;
    this.value1 = value1;
    this.value2 = value2;
  }

  toMap(): TypedMap<string, ethereum.Value> {
    let map = new TypedMap<string, ethereum.Value>();
    map.set("value0", ethereum.Value.fromUnsignedBigInt(this.value0));
    map.set("value1", ethereum.Value.fromI32(this.value1));
    map.set("value2", ethereum.Value.fromI32(this.value2));
    return map;
  }

  getLiquidity(): BigInt {
    return this.value0;
  }

  getTickLower(): i32 {
    return this.value1;
  }

  getTickUpper(): i32 {
    return this.value2;
  }
}

export class LimitFarming__getRewardInfoResult {
  value0: BigInt;
  value1: BigInt;

  constructor(value0: BigInt, value1: BigInt) {
    this.value0 = value0;
    this.value1 = value1;
  }

  toMap(): TypedMap<string, ethereum.Value> {
    let map = new TypedMap<string, ethereum.Value>();
    map.set("value0", ethereum.Value.fromUnsignedBigInt(this.value0));
    map.set("value1", ethereum.Value.fromUnsignedBigInt(this.value1));
    return map;
  }

  getReward(): BigInt {
    return this.value0;
  }

  getBonusReward(): BigInt {
    return this.value1;
  }
}

export class LimitFarming__getRewardInfoInputKeyStruct extends ethereum.Tuple {
  get rewardToken(): Address {
    return this[0].toAddress();
  }

  get bonusRewardToken(): Address {
    return this[1].toAddress();
  }

  get pool(): Address {
    return this[2].toAddress();
  }

  get startTime(): BigInt {
    return this[3].toBigInt();
  }

  get endTime(): BigInt {
    return this[4].toBigInt();
  }
}

export class LimitFarming__incentivesResultTiersStruct extends ethereum.Tuple {
  get tokenAmountForTier1(): BigInt {
    return this[0].toBigInt();
  }

  get tokenAmountForTier2(): BigInt {
    return this[1].toBigInt();
  }

  get tokenAmountForTier3(): BigInt {
    return this[2].toBigInt();
  }

  get tier1Multiplier(): BigInt {
    return this[3].toBigInt();
  }

  get tier2Multiplier(): BigInt {
    return this[4].toBigInt();
  }

  get tier3Multiplier(): BigInt {
    return this[5].toBigInt();
  }
}

export class LimitFarming__incentivesResult {
  value0: BigInt;
  value1: BigInt;
  value2: Address;
  value3: i32;
  value4: BigInt;
  value5: Address;
  value6: LimitFarming__incentivesResultTiersStruct;

  constructor(
    value0: BigInt,
    value1: BigInt,
    value2: Address,
    value3: i32,
    value4: BigInt,
    value5: Address,
    value6: LimitFarming__incentivesResultTiersStruct,
  ) {
    this.value0 = value0;
    this.value1 = value1;
    this.value2 = value2;
    this.value3 = value3;
    this.value4 = value4;
    this.value5 = value5;
    this.value6 = value6;
  }

  toMap(): TypedMap<string, ethereum.Value> {
    let map = new TypedMap<string, ethereum.Value>();
    map.set("value0", ethereum.Value.fromUnsignedBigInt(this.value0));
    map.set("value1", ethereum.Value.fromUnsignedBigInt(this.value1));
    map.set("value2", ethereum.Value.fromAddress(this.value2));
    map.set(
      "value3",
      ethereum.Value.fromUnsignedBigInt(BigInt.fromI32(this.value3)),
    );
    map.set("value4", ethereum.Value.fromUnsignedBigInt(this.value4));
    map.set("value5", ethereum.Value.fromAddress(this.value5));
    map.set("value6", ethereum.Value.fromTuple(this.value6));
    return map;
  }

  getTotalReward(): BigInt {
    return this.value0;
  }

  getBonusReward(): BigInt {
    return this.value1;
  }

  getVirtualPoolAddress(): Address {
    return this.value2;
  }

  getMinimalPositionWidth(): i32 {
    return this.value3;
  }

  getTotalLiquidity(): BigInt {
    return this.value4;
  }

  getMultiplierToken(): Address {
    return this.value5;
  }

  getTiers(): LimitFarming__incentivesResultTiersStruct {
    return this.value6;
  }
}

export class LimitFarming extends ethereum.SmartContract {
  static bind(address: Address): LimitFarming {
    return new LimitFarming("LimitFarming", address);
  }

  claimReward(
    rewardToken: Address,
    to: Address,
    amountRequested: BigInt,
  ): BigInt {
    let result = super.call(
      "claimReward",
      "claimReward(address,address,uint256):(uint256)",
      [
        ethereum.Value.fromAddress(rewardToken),
        ethereum.Value.fromAddress(to),
        ethereum.Value.fromUnsignedBigInt(amountRequested),
      ],
    );

    return result[0].toBigInt();
  }

  try_claimReward(
    rewardToken: Address,
    to: Address,
    amountRequested: BigInt,
  ): ethereum.CallResult<BigInt> {
    let result = super.tryCall(
      "claimReward",
      "claimReward(address,address,uint256):(uint256)",
      [
        ethereum.Value.fromAddress(rewardToken),
        ethereum.Value.fromAddress(to),
        ethereum.Value.fromUnsignedBigInt(amountRequested),
      ],
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBigInt());
  }

  claimRewardFrom(
    rewardToken: Address,
    from: Address,
    to: Address,
    amountRequested: BigInt,
  ): BigInt {
    let result = super.call(
      "claimRewardFrom",
      "claimRewardFrom(address,address,address,uint256):(uint256)",
      [
        ethereum.Value.fromAddress(rewardToken),
        ethereum.Value.fromAddress(from),
        ethereum.Value.fromAddress(to),
        ethereum.Value.fromUnsignedBigInt(amountRequested),
      ],
    );

    return result[0].toBigInt();
  }

  try_claimRewardFrom(
    rewardToken: Address,
    from: Address,
    to: Address,
    amountRequested: BigInt,
  ): ethereum.CallResult<BigInt> {
    let result = super.tryCall(
      "claimRewardFrom",
      "claimRewardFrom(address,address,address,uint256):(uint256)",
      [
        ethereum.Value.fromAddress(rewardToken),
        ethereum.Value.fromAddress(from),
        ethereum.Value.fromAddress(to),
        ethereum.Value.fromUnsignedBigInt(amountRequested),
      ],
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBigInt());
  }

  createLimitFarming(
    key: LimitFarming__createLimitFarmingInputKeyStruct,
    tiers: LimitFarming__createLimitFarmingInputTiersStruct,
    params: LimitFarming__createLimitFarmingInputParamsStruct,
  ): Address {
    let result = super.call(
      "createLimitFarming",
      "createLimitFarming((address,address,address,uint256,uint256),(uint256,uint256,uint256,uint32,uint32,uint32),(uint256,uint256,uint24,address,uint32)):(address)",
      [
        ethereum.Value.fromTuple(key),
        ethereum.Value.fromTuple(tiers),
        ethereum.Value.fromTuple(params),
      ],
    );

    return result[0].toAddress();
  }

  try_createLimitFarming(
    key: LimitFarming__createLimitFarmingInputKeyStruct,
    tiers: LimitFarming__createLimitFarmingInputTiersStruct,
    params: LimitFarming__createLimitFarmingInputParamsStruct,
  ): ethereum.CallResult<Address> {
    let result = super.tryCall(
      "createLimitFarming",
      "createLimitFarming((address,address,address,uint256,uint256),(uint256,uint256,uint256,uint32,uint32,uint32),(uint256,uint256,uint24,address,uint32)):(address)",
      [
        ethereum.Value.fromTuple(key),
        ethereum.Value.fromTuple(tiers),
        ethereum.Value.fromTuple(params),
      ],
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toAddress());
  }

  deployer(): Address {
    let result = super.call("deployer", "deployer():(address)", []);

    return result[0].toAddress();
  }

  try_deployer(): ethereum.CallResult<Address> {
    let result = super.tryCall("deployer", "deployer():(address)", []);
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toAddress());
  }

  farmingCenter(): Address {
    let result = super.call("farmingCenter", "farmingCenter():(address)", []);

    return result[0].toAddress();
  }

  try_farmingCenter(): ethereum.CallResult<Address> {
    let result = super.tryCall(
      "farmingCenter",
      "farmingCenter():(address)",
      [],
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toAddress());
  }

  farms(param0: BigInt, param1: Bytes): LimitFarming__farmsResult {
    let result = super.call(
      "farms",
      "farms(uint256,bytes32):(uint128,int24,int24)",
      [
        ethereum.Value.fromUnsignedBigInt(param0),
        ethereum.Value.fromFixedBytes(param1),
      ],
    );

    return new LimitFarming__farmsResult(
      result[0].toBigInt(),
      result[1].toI32(),
      result[2].toI32(),
    );
  }

  try_farms(
    param0: BigInt,
    param1: Bytes,
  ): ethereum.CallResult<LimitFarming__farmsResult> {
    let result = super.tryCall(
      "farms",
      "farms(uint256,bytes32):(uint128,int24,int24)",
      [
        ethereum.Value.fromUnsignedBigInt(param0),
        ethereum.Value.fromFixedBytes(param1),
      ],
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(
      new LimitFarming__farmsResult(
        value[0].toBigInt(),
        value[1].toI32(),
        value[2].toI32(),
      ),
    );
  }

  getRewardInfo(
    key: LimitFarming__getRewardInfoInputKeyStruct,
    tokenId: BigInt,
  ): LimitFarming__getRewardInfoResult {
    let result = super.call(
      "getRewardInfo",
      "getRewardInfo((address,address,address,uint256,uint256),uint256):(uint256,uint256)",
      [
        ethereum.Value.fromTuple(key),
        ethereum.Value.fromUnsignedBigInt(tokenId),
      ],
    );

    return new LimitFarming__getRewardInfoResult(
      result[0].toBigInt(),
      result[1].toBigInt(),
    );
  }

  try_getRewardInfo(
    key: LimitFarming__getRewardInfoInputKeyStruct,
    tokenId: BigInt,
  ): ethereum.CallResult<LimitFarming__getRewardInfoResult> {
    let result = super.tryCall(
      "getRewardInfo",
      "getRewardInfo((address,address,address,uint256,uint256),uint256):(uint256,uint256)",
      [
        ethereum.Value.fromTuple(key),
        ethereum.Value.fromUnsignedBigInt(tokenId),
      ],
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(
      new LimitFarming__getRewardInfoResult(
        value[0].toBigInt(),
        value[1].toBigInt(),
      ),
    );
  }

  incentives(param0: Bytes): LimitFarming__incentivesResult {
    let result = super.call(
      "incentives",
      "incentives(bytes32):(uint256,uint256,address,uint24,uint224,address,(uint256,uint256,uint256,uint32,uint32,uint32))",
      [ethereum.Value.fromFixedBytes(param0)],
    );

    return new LimitFarming__incentivesResult(
      result[0].toBigInt(),
      result[1].toBigInt(),
      result[2].toAddress(),
      result[3].toI32(),
      result[4].toBigInt(),
      result[5].toAddress(),
      changetype<LimitFarming__incentivesResultTiersStruct>(
        result[6].toTuple(),
      ),
    );
  }

  try_incentives(
    param0: Bytes,
  ): ethereum.CallResult<LimitFarming__incentivesResult> {
    let result = super.tryCall(
      "incentives",
      "incentives(bytes32):(uint256,uint256,address,uint24,uint224,address,(uint256,uint256,uint256,uint32,uint32,uint32))",
      [ethereum.Value.fromFixedBytes(param0)],
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(
      new LimitFarming__incentivesResult(
        value[0].toBigInt(),
        value[1].toBigInt(),
        value[2].toAddress(),
        value[3].toI32(),
        value[4].toBigInt(),
        value[5].toAddress(),
        changetype<LimitFarming__incentivesResultTiersStruct>(
          value[6].toTuple(),
        ),
      ),
    );
  }

  maxIncentiveDuration(): BigInt {
    let result = super.call(
      "maxIncentiveDuration",
      "maxIncentiveDuration():(uint256)",
      [],
    );

    return result[0].toBigInt();
  }

  try_maxIncentiveDuration(): ethereum.CallResult<BigInt> {
    let result = super.tryCall(
      "maxIncentiveDuration",
      "maxIncentiveDuration():(uint256)",
      [],
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBigInt());
  }

  maxIncentiveStartLeadTime(): BigInt {
    let result = super.call(
      "maxIncentiveStartLeadTime",
      "maxIncentiveStartLeadTime():(uint256)",
      [],
    );

    return result[0].toBigInt();
  }

  try_maxIncentiveStartLeadTime(): ethereum.CallResult<BigInt> {
    let result = super.tryCall(
      "maxIncentiveStartLeadTime",
      "maxIncentiveStartLeadTime():(uint256)",
      [],
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBigInt());
  }

  nonfungiblePositionManager(): Address {
    let result = super.call(
      "nonfungiblePositionManager",
      "nonfungiblePositionManager():(address)",
      [],
    );

    return result[0].toAddress();
  }

  try_nonfungiblePositionManager(): ethereum.CallResult<Address> {
    let result = super.tryCall(
      "nonfungiblePositionManager",
      "nonfungiblePositionManager():(address)",
      [],
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toAddress());
  }

  rewards(param0: Address, param1: Address): BigInt {
    let result = super.call("rewards", "rewards(address,address):(uint256)", [
      ethereum.Value.fromAddress(param0),
      ethereum.Value.fromAddress(param1),
    ]);

    return result[0].toBigInt();
  }

  try_rewards(param0: Address, param1: Address): ethereum.CallResult<BigInt> {
    let result = super.tryCall(
      "rewards",
      "rewards(address,address):(uint256)",
      [ethereum.Value.fromAddress(param0), ethereum.Value.fromAddress(param1)],
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBigInt());
  }
}

export class ConstructorCall extends ethereum.Call {
  get inputs(): ConstructorCall__Inputs {
    return new ConstructorCall__Inputs(this);
  }

  get outputs(): ConstructorCall__Outputs {
    return new ConstructorCall__Outputs(this);
  }
}

export class ConstructorCall__Inputs {
  _call: ConstructorCall;

  constructor(call: ConstructorCall) {
    this._call = call;
  }

  get _deployer(): Address {
    return this._call.inputValues[0].value.toAddress();
  }

  get _nonfungiblePositionManager(): Address {
    return this._call.inputValues[1].value.toAddress();
  }

  get _maxIncentiveStartLeadTime(): BigInt {
    return this._call.inputValues[2].value.toBigInt();
  }

  get _maxIncentiveDuration(): BigInt {
    return this._call.inputValues[3].value.toBigInt();
  }
}

export class ConstructorCall__Outputs {
  _call: ConstructorCall;

  constructor(call: ConstructorCall) {
    this._call = call;
  }
}

export class AddRewardsCall extends ethereum.Call {
  get inputs(): AddRewardsCall__Inputs {
    return new AddRewardsCall__Inputs(this);
  }

  get outputs(): AddRewardsCall__Outputs {
    return new AddRewardsCall__Outputs(this);
  }
}

export class AddRewardsCall__Inputs {
  _call: AddRewardsCall;

  constructor(call: AddRewardsCall) {
    this._call = call;
  }

  get key(): AddRewardsCallKeyStruct {
    return changetype<AddRewardsCallKeyStruct>(
      this._call.inputValues[0].value.toTuple(),
    );
  }

  get reward(): BigInt {
    return this._call.inputValues[1].value.toBigInt();
  }

  get bonusReward(): BigInt {
    return this._call.inputValues[2].value.toBigInt();
  }
}

export class AddRewardsCall__Outputs {
  _call: AddRewardsCall;

  constructor(call: AddRewardsCall) {
    this._call = call;
  }
}

export class AddRewardsCallKeyStruct extends ethereum.Tuple {
  get rewardToken(): Address {
    return this[0].toAddress();
  }

  get bonusRewardToken(): Address {
    return this[1].toAddress();
  }

  get pool(): Address {
    return this[2].toAddress();
  }

  get startTime(): BigInt {
    return this[3].toBigInt();
  }

  get endTime(): BigInt {
    return this[4].toBigInt();
  }
}

export class AttachIncentiveCall extends ethereum.Call {
  get inputs(): AttachIncentiveCall__Inputs {
    return new AttachIncentiveCall__Inputs(this);
  }

  get outputs(): AttachIncentiveCall__Outputs {
    return new AttachIncentiveCall__Outputs(this);
  }
}

export class AttachIncentiveCall__Inputs {
  _call: AttachIncentiveCall;

  constructor(call: AttachIncentiveCall) {
    this._call = call;
  }

  get key(): AttachIncentiveCallKeyStruct {
    return changetype<AttachIncentiveCallKeyStruct>(
      this._call.inputValues[0].value.toTuple(),
    );
  }
}

export class AttachIncentiveCall__Outputs {
  _call: AttachIncentiveCall;

  constructor(call: AttachIncentiveCall) {
    this._call = call;
  }
}

export class AttachIncentiveCallKeyStruct extends ethereum.Tuple {
  get rewardToken(): Address {
    return this[0].toAddress();
  }

  get bonusRewardToken(): Address {
    return this[1].toAddress();
  }

  get pool(): Address {
    return this[2].toAddress();
  }

  get startTime(): BigInt {
    return this[3].toBigInt();
  }

  get endTime(): BigInt {
    return this[4].toBigInt();
  }
}

export class ClaimRewardCall extends ethereum.Call {
  get inputs(): ClaimRewardCall__Inputs {
    return new ClaimRewardCall__Inputs(this);
  }

  get outputs(): ClaimRewardCall__Outputs {
    return new ClaimRewardCall__Outputs(this);
  }
}

export class ClaimRewardCall__Inputs {
  _call: ClaimRewardCall;

  constructor(call: ClaimRewardCall) {
    this._call = call;
  }

  get rewardToken(): Address {
    return this._call.inputValues[0].value.toAddress();
  }

  get to(): Address {
    return this._call.inputValues[1].value.toAddress();
  }

  get amountRequested(): BigInt {
    return this._call.inputValues[2].value.toBigInt();
  }
}

export class ClaimRewardCall__Outputs {
  _call: ClaimRewardCall;

  constructor(call: ClaimRewardCall) {
    this._call = call;
  }

  get reward(): BigInt {
    return this._call.outputValues[0].value.toBigInt();
  }
}

export class ClaimRewardFromCall extends ethereum.Call {
  get inputs(): ClaimRewardFromCall__Inputs {
    return new ClaimRewardFromCall__Inputs(this);
  }

  get outputs(): ClaimRewardFromCall__Outputs {
    return new ClaimRewardFromCall__Outputs(this);
  }
}

export class ClaimRewardFromCall__Inputs {
  _call: ClaimRewardFromCall;

  constructor(call: ClaimRewardFromCall) {
    this._call = call;
  }

  get rewardToken(): Address {
    return this._call.inputValues[0].value.toAddress();
  }

  get from(): Address {
    return this._call.inputValues[1].value.toAddress();
  }

  get to(): Address {
    return this._call.inputValues[2].value.toAddress();
  }

  get amountRequested(): BigInt {
    return this._call.inputValues[3].value.toBigInt();
  }
}

export class ClaimRewardFromCall__Outputs {
  _call: ClaimRewardFromCall;

  constructor(call: ClaimRewardFromCall) {
    this._call = call;
  }

  get reward(): BigInt {
    return this._call.outputValues[0].value.toBigInt();
  }
}

export class CreateLimitFarmingCall extends ethereum.Call {
  get inputs(): CreateLimitFarmingCall__Inputs {
    return new CreateLimitFarmingCall__Inputs(this);
  }

  get outputs(): CreateLimitFarmingCall__Outputs {
    return new CreateLimitFarmingCall__Outputs(this);
  }
}

export class CreateLimitFarmingCall__Inputs {
  _call: CreateLimitFarmingCall;

  constructor(call: CreateLimitFarmingCall) {
    this._call = call;
  }

  get key(): CreateLimitFarmingCallKeyStruct {
    return changetype<CreateLimitFarmingCallKeyStruct>(
      this._call.inputValues[0].value.toTuple(),
    );
  }

  get tiers(): CreateLimitFarmingCallTiersStruct {
    return changetype<CreateLimitFarmingCallTiersStruct>(
      this._call.inputValues[1].value.toTuple(),
    );
  }

  get params(): CreateLimitFarmingCallParamsStruct {
    return changetype<CreateLimitFarmingCallParamsStruct>(
      this._call.inputValues[2].value.toTuple(),
    );
  }
}

export class CreateLimitFarmingCall__Outputs {
  _call: CreateLimitFarmingCall;

  constructor(call: CreateLimitFarmingCall) {
    this._call = call;
  }

  get virtualPool(): Address {
    return this._call.outputValues[0].value.toAddress();
  }
}

export class CreateLimitFarmingCallKeyStruct extends ethereum.Tuple {
  get rewardToken(): Address {
    return this[0].toAddress();
  }

  get bonusRewardToken(): Address {
    return this[1].toAddress();
  }

  get pool(): Address {
    return this[2].toAddress();
  }

  get startTime(): BigInt {
    return this[3].toBigInt();
  }

  get endTime(): BigInt {
    return this[4].toBigInt();
  }
}

export class CreateLimitFarmingCallTiersStruct extends ethereum.Tuple {
  get tokenAmountForTier1(): BigInt {
    return this[0].toBigInt();
  }

  get tokenAmountForTier2(): BigInt {
    return this[1].toBigInt();
  }

  get tokenAmountForTier3(): BigInt {
    return this[2].toBigInt();
  }

  get tier1Multiplier(): BigInt {
    return this[3].toBigInt();
  }

  get tier2Multiplier(): BigInt {
    return this[4].toBigInt();
  }

  get tier3Multiplier(): BigInt {
    return this[5].toBigInt();
  }
}

export class CreateLimitFarmingCallParamsStruct extends ethereum.Tuple {
  get reward(): BigInt {
    return this[0].toBigInt();
  }

  get bonusReward(): BigInt {
    return this[1].toBigInt();
  }

  get minimalPositionWidth(): i32 {
    return this[2].toI32();
  }

  get multiplierToken(): Address {
    return this[3].toAddress();
  }

  get enterStartTime(): BigInt {
    return this[4].toBigInt();
  }
}

export class DecreaseRewardsAmountCall extends ethereum.Call {
  get inputs(): DecreaseRewardsAmountCall__Inputs {
    return new DecreaseRewardsAmountCall__Inputs(this);
  }

  get outputs(): DecreaseRewardsAmountCall__Outputs {
    return new DecreaseRewardsAmountCall__Outputs(this);
  }
}

export class DecreaseRewardsAmountCall__Inputs {
  _call: DecreaseRewardsAmountCall;

  constructor(call: DecreaseRewardsAmountCall) {
    this._call = call;
  }

  get key(): DecreaseRewardsAmountCallKeyStruct {
    return changetype<DecreaseRewardsAmountCallKeyStruct>(
      this._call.inputValues[0].value.toTuple(),
    );
  }

  get rewardAmount(): BigInt {
    return this._call.inputValues[1].value.toBigInt();
  }

  get bonusRewardAmount(): BigInt {
    return this._call.inputValues[2].value.toBigInt();
  }
}

export class DecreaseRewardsAmountCall__Outputs {
  _call: DecreaseRewardsAmountCall;

  constructor(call: DecreaseRewardsAmountCall) {
    this._call = call;
  }
}

export class DecreaseRewardsAmountCallKeyStruct extends ethereum.Tuple {
  get rewardToken(): Address {
    return this[0].toAddress();
  }

  get bonusRewardToken(): Address {
    return this[1].toAddress();
  }

  get pool(): Address {
    return this[2].toAddress();
  }

  get startTime(): BigInt {
    return this[3].toBigInt();
  }

  get endTime(): BigInt {
    return this[4].toBigInt();
  }
}

export class DetachIncentiveCall extends ethereum.Call {
  get inputs(): DetachIncentiveCall__Inputs {
    return new DetachIncentiveCall__Inputs(this);
  }

  get outputs(): DetachIncentiveCall__Outputs {
    return new DetachIncentiveCall__Outputs(this);
  }
}

export class DetachIncentiveCall__Inputs {
  _call: DetachIncentiveCall;

  constructor(call: DetachIncentiveCall) {
    this._call = call;
  }

  get key(): DetachIncentiveCallKeyStruct {
    return changetype<DetachIncentiveCallKeyStruct>(
      this._call.inputValues[0].value.toTuple(),
    );
  }
}

export class DetachIncentiveCall__Outputs {
  _call: DetachIncentiveCall;

  constructor(call: DetachIncentiveCall) {
    this._call = call;
  }
}

export class DetachIncentiveCallKeyStruct extends ethereum.Tuple {
  get rewardToken(): Address {
    return this[0].toAddress();
  }

  get bonusRewardToken(): Address {
    return this[1].toAddress();
  }

  get pool(): Address {
    return this[2].toAddress();
  }

  get startTime(): BigInt {
    return this[3].toBigInt();
  }

  get endTime(): BigInt {
    return this[4].toBigInt();
  }
}

export class EnterFarmingCall extends ethereum.Call {
  get inputs(): EnterFarmingCall__Inputs {
    return new EnterFarmingCall__Inputs(this);
  }

  get outputs(): EnterFarmingCall__Outputs {
    return new EnterFarmingCall__Outputs(this);
  }
}

export class EnterFarmingCall__Inputs {
  _call: EnterFarmingCall;

  constructor(call: EnterFarmingCall) {
    this._call = call;
  }

  get key(): EnterFarmingCallKeyStruct {
    return changetype<EnterFarmingCallKeyStruct>(
      this._call.inputValues[0].value.toTuple(),
    );
  }

  get tokenId(): BigInt {
    return this._call.inputValues[1].value.toBigInt();
  }

  get tokensLocked(): BigInt {
    return this._call.inputValues[2].value.toBigInt();
  }
}

export class EnterFarmingCall__Outputs {
  _call: EnterFarmingCall;

  constructor(call: EnterFarmingCall) {
    this._call = call;
  }
}

export class EnterFarmingCallKeyStruct extends ethereum.Tuple {
  get rewardToken(): Address {
    return this[0].toAddress();
  }

  get bonusRewardToken(): Address {
    return this[1].toAddress();
  }

  get pool(): Address {
    return this[2].toAddress();
  }

  get startTime(): BigInt {
    return this[3].toBigInt();
  }

  get endTime(): BigInt {
    return this[4].toBigInt();
  }
}

export class ExitFarmingCall extends ethereum.Call {
  get inputs(): ExitFarmingCall__Inputs {
    return new ExitFarmingCall__Inputs(this);
  }

  get outputs(): ExitFarmingCall__Outputs {
    return new ExitFarmingCall__Outputs(this);
  }
}

export class ExitFarmingCall__Inputs {
  _call: ExitFarmingCall;

  constructor(call: ExitFarmingCall) {
    this._call = call;
  }

  get key(): ExitFarmingCallKeyStruct {
    return changetype<ExitFarmingCallKeyStruct>(
      this._call.inputValues[0].value.toTuple(),
    );
  }

  get tokenId(): BigInt {
    return this._call.inputValues[1].value.toBigInt();
  }

  get _owner(): Address {
    return this._call.inputValues[2].value.toAddress();
  }
}

export class ExitFarmingCall__Outputs {
  _call: ExitFarmingCall;

  constructor(call: ExitFarmingCall) {
    this._call = call;
  }
}

export class ExitFarmingCallKeyStruct extends ethereum.Tuple {
  get rewardToken(): Address {
    return this[0].toAddress();
  }

  get bonusRewardToken(): Address {
    return this[1].toAddress();
  }

  get pool(): Address {
    return this[2].toAddress();
  }

  get startTime(): BigInt {
    return this[3].toBigInt();
  }

  get endTime(): BigInt {
    return this[4].toBigInt();
  }
}

export class SetFarmingCenterAddressCall extends ethereum.Call {
  get inputs(): SetFarmingCenterAddressCall__Inputs {
    return new SetFarmingCenterAddressCall__Inputs(this);
  }

  get outputs(): SetFarmingCenterAddressCall__Outputs {
    return new SetFarmingCenterAddressCall__Outputs(this);
  }
}

export class SetFarmingCenterAddressCall__Inputs {
  _call: SetFarmingCenterAddressCall;

  constructor(call: SetFarmingCenterAddressCall) {
    this._call = call;
  }

  get _farmingCenter(): Address {
    return this._call.inputValues[0].value.toAddress();
  }
}

export class SetFarmingCenterAddressCall__Outputs {
  _call: SetFarmingCenterAddressCall;

  constructor(call: SetFarmingCenterAddressCall) {
    this._call = call;
  }
}

export class SetIncentiveMakerCall extends ethereum.Call {
  get inputs(): SetIncentiveMakerCall__Inputs {
    return new SetIncentiveMakerCall__Inputs(this);
  }

  get outputs(): SetIncentiveMakerCall__Outputs {
    return new SetIncentiveMakerCall__Outputs(this);
  }
}

export class SetIncentiveMakerCall__Inputs {
  _call: SetIncentiveMakerCall;

  constructor(call: SetIncentiveMakerCall) {
    this._call = call;
  }

  get _incentiveMaker(): Address {
    return this._call.inputValues[0].value.toAddress();
  }
}

export class SetIncentiveMakerCall__Outputs {
  _call: SetIncentiveMakerCall;

  constructor(call: SetIncentiveMakerCall) {
    this._call = call;
  }
}
